server:
  port: 9000

spring:

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS local
    username: sa
    password:

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true